CREATE TABLE IF NOT EXISTS neighborhood (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying
);
--;;
CREATE UNIQUE INDEX index_neighborhood_on_name ON neighborhood(name);
--;;
INSERT INTO neighborhood (name) VALUES
('Chelsea'),
('Chinatown'),
('DUMBO'),
('East Village'),
('Greenwich Village'),
('Harlem'),
('Long Island City'),
('Lower East Side'),
('Midtown'),
('Park Slope'),
('Prospect Heights'),
('Red Hook'),
('Soho'),
('Tribeca'),
('Upper East Side'),
('Upper West Side');
