CREATE TABLE IF NOT EXISTS neighborhood (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying
);
--;;
CREATE UNIQUE INDEX index_neighborhood_on_name ON neighborhood(name);
